services:
  redis:
    image: redis:latest
    container_name: container_redis
    ports:
      - "6379:6379"
    networks:
      - sys_net
    volumes:
      - /redis:/redis
    restart: unless-stopped

  vid:
    build:
      context: ./vid
    ports:
      - "1375:1375"
    networks:
      - sys_net
    container_name: container_vid
    environment:
      - VID_IP=0.0.0.0
      - VID_PORT=1375
      - REDIS_PORT=6379
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./vid:/usr/src/app
      - ./utils:/usr/src/app/utils    
      - ../logs:/usr/src/app/logs
      - /models:/models
      - /tmp:/tmp
    runtime: nvidia
    depends_on:
      - redis
    restart: unless-stopped
    
networks:
  sys_net:
    name: sys_net
    driver: bridge